name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: paper
          root_file: article.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode --shell-escape
          extra_system_packages: inkscape
      - name: Upload pdf
        uses: EndBug/add-and-commit@v9
        with:
          pull: true
          add: paper/article.pdf
          message: 'Update pdf'
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
